name:                file-server-api
version:             0.1.0.0
github:              JenningsIRE/file-server-api
license:             BSD3
author:              Sam Jennings
maintainer:          jennins@tcd.ie
copyright:           Copyright (C) 2017

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            assignment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/JenningsIRE/file-server-api#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  file-server-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-server-api

tests:
  file-server-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - file-server-api
